{% set name = "ahlive" %}
{% set version = "1.0.4.post1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ahlive-{{ version }}.tar.gz
  sha256: b553dd479601045696685ba6e6e331ec91ada36226b439265218d05ff9845761

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools-scm
    - setuptools >=30.3.0
    - setuptools_scm_git_archive
    - pip
  run:
    - python >={{ python_min }}
    - param <2.0.0
    - numpy
    - pandas
    - bottleneck
    - xarray >=0.16.1
    - matplotlib-base >=3.3
    - imageio

test:
  imports:
    - ahlive
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/ahuang11/ahlive
  summary: animate your data to life
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
